User API init
avantifellows/db-service-backend pull request #1
Opened 2022-03-24 20:08 UTC by rathorevaibhav

### Summary

1. Controller, schema (model), and migrations for User
2. User right now have only sample columns like first_name, last_name, email and phone. More columns will come in later
3.

2022-03-25 09:31 UTC, pritamps requested changes
Hey @rathorevaibhav , considering the scope of this db, can we rename the repo to `af-db-backend`? Remove references to `portal` and repalce with `af-db` 

This looks cool! You will have to give a walkthrough of the code :)

2022-03-25 09:31 UTC, pritamps commented on lib/portal/users.ex
> +    |> User.changeset(attrs)
Do we need some checknig on the `attrs` here?

2022-03-25 09:56 UTC, sudheshna-donthineni commented on lib/portal/users.ex
> +    Repo.all(User)
For analytics, we might need. Is there a downside to having it?

2022-03-25 11:02 UTC, pritamps commented on lib/portal/users.ex
> +    Repo.all(User)
It doens't make sense to have a call that will return 10k-20k-1M users, no? WIll be very painful for the database. For analytics, we'll use BigQuery which will do this properly.

2022-03-29 06:32 UTC, sudheshna-donthineni commented on lib/portal/users.ex
> +    Repo.all(User)
Makes sense. I keep forgetting about transactional vs analytics.

2022-03-29 17:46 UTC, closed without merging