Minor schema changes
avantifellows/db-service-backend pull request #39
Opened 2022-10-18 10:22 UTC by Bahugunajii

2022-10-25 06:51 UTC, rathorevaibhav requested changes

2022-10-26 10:23 UTC, Bahugunajii commented on lib/dbservice/sessions/session.ex
> +  defp validate_date_time(changeset) do
Done!

2022-10-26 10:23 UTC, Bahugunajii commented on priv/repo/migrations/20221018090238_modify_group_user.exs
> +      modify :updated_at, :utc_datetime, default: fragment("NOW()")
Done!

2022-10-26 14:53 UTC, rathorevaibhav commented on lib/dbservice/groups/group.ex
> +    invalidate_future_date(changeset, :program_start_date)
nice!

2022-10-26 15:32 UTC, Bahugunajii commented on priv/repo/migrations/20221018090242_modify_group_session.exs
> +      modify :updated_at, :utc_datetime, default: fragment("NOW()")
Yes!

2022-10-26 16:42 UTC, rathorevaibhav approved these changes

2022-10-26 16:42 UTC, merged